name: flutter_steps_tracker
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # this package for localizations
  flutter_localizations:
    sdk: flutter

  # this package for steps counter
  pedometer: ^3.0.0

  # this packages for firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17

  # this packages for injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  # this packages for state management
  provider: ^6.0.3
  flutter_bloc: ^8.0.1

  # this package for local data base
  shared_preferences: ^2.0.15

  # this package for bottom nav bar
  persistent_bottom_nav_bar_v2: ^4.2.3

  # this packages for images
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.5

  # this packages for create class helper us in devlope
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  dartz: ^0.10.1
  equatable: ^2.0.3
  logging: ^1.0.2

  # this packages for time and date 
  intl: ^0.17.0
  cron: ^0.5.0

  # this package for guages and she is contain animations
  syncfusion_flutter_gauges: ^20.1.59

  # this package for permission to count the steps
  permission_handler: ^10.0.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  injectable_generator: ^1.5.3
  change_app_package_name: ^1.1.0

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/svg/